### ISSUE TITLE
when can we release 1.0.0?

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/pgdown#20]
@deanlandolt Any thoughts on this?

**Comment by ralphtheninja** [comment]
When we decide to release it, then we can move it to the `Level` org first, fix package.json and links and shit before relasing 1.0.0 into the wild.

**Comment by deanlandolt** [comment]
I want to flesh out the sublevel and live stream before any release (let alone 1.0). I created a postgres-level repo to house this stuff since it's not strictly necessary for pgdown, but pgdown definitely needs to be aware of it. I also want to fix up the null-byte encoding stuff and do it in a way we can move this crap out of pgdown as well. I'd also like to use a better approach to how we're storing transactions that will allow us to do smart operation buffering and surface the ability to grab iterators on recent commits (should be really easy, have no notable perf impact, and be actually make live streams reliable/useful even in the face of reconnects).

This may seem like a big list but individually these are all pretty straight-forward. But we definitely need to get the underlying table structures fully fleshed out before any 1.0.0, since I really don't want to have to think about migration shit. (Another reason I'm going to move out the text/jsonb stuff to postgres-level and just implement w/ views -- this will allow pgdown to just do what it does, and let us lay indexing shit on top and still remain backward compatible w/o having to do a bunch of `ALTER` bullshit to patch up tables when they change).
